// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(AdventureWorks2012_aContext))]
    [Migration("20250906140336_InialCreate")]
    partial class InialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Department", b =>
                {
                    b.Property<short>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasComment("Primary key for Department records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("DepartmentID"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the group to which the department belongs.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the department.");

                    b.Property<bool?>("status")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID")
                        .HasName("PK_Department_DepartmentID");

                    b.HasIndex(new[] { "Name" }, "AK_Department_Name")
                        .IsUnique();

                    b.ToTable("Department", "HumanResources", t =>
                        {
                            t.HasComment("Lookup table containing the departments within the Adventure Works Cycles company.");
                        });
                });

            modelBuilder.Entity("Data.Models.Employee", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Primary key for Employee records.  Foreign key to BusinessEntity.BusinessEntityID.");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("Date of birth.");

                    b.Property<bool>("CurrentFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("0 = Inactive, 1 = Active");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Male, F = Female");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasComment("Employee hired on this date.");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Work title such as Buyer or Sales Representative.");

                    b.Property<string>("LoginID")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Network login.");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength()
                        .HasComment("M = Married, S = Single");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Unique national identification number such as a social security number.");

                    b.Property<short?>("OrganizationLevel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("smallint")
                        .HasComputedColumnSql("([OrganizationNode].[GetLevel]())", false)
                        .HasComment("The depth of the employee in the corporate hierarchy.");

                    b.Property<bool>("SalariedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Job classification. 0 = Hourly, not exempt from collective bargaining. 1 = Salaried, exempt from collective bargaining.");

                    b.Property<short>("SickLeaveHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available sick leave hours.");

                    b.Property<short>("VacationHours")
                        .HasColumnType("smallint")
                        .HasComment("Number of available vacation hours.");

                    b.Property<Guid>("rowguid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())")
                        .HasComment("ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.");

                    b.HasKey("BusinessEntityID")
                        .HasName("PK_Employee_BusinessEntityID");

                    b.HasIndex(new[] { "LoginID" }, "AK_Employee_LoginID")
                        .IsUnique();

                    b.HasIndex(new[] { "NationalIDNumber" }, "AK_Employee_NationalIDNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "rowguid" }, "AK_Employee_rowguid")
                        .IsUnique();

                    b.ToTable("Employee", "HumanResources", t =>
                        {
                            t.HasComment("Employee information such as salary, department, and title.");

                            t.HasTrigger("dEmployee");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Data.Models.EmployeeDepartmentHistory", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number. Foreign key to Employee.BusinessEntityID.");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasComment("Date the employee started work in the department.");

                    b.Property<short>("DepartmentID")
                        .HasColumnType("smallint")
                        .HasComment("Department in which the employee worked including currently. Foreign key to Department.DepartmentID.");

                    b.Property<byte>("ShiftID")
                        .HasColumnType("tinyint")
                        .HasComment("Identifies which 8-hour shift the employee works. Foreign key to Shift.Shift.ID.");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasComment("Date the employee left the department. NULL = Current department.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.HasKey("BusinessEntityID", "StartDate", "DepartmentID", "ShiftID")
                        .HasName("PK_EmployeeDepartmentHistory_BusinessEntityID_StartDate_DepartmentID");

                    b.HasIndex(new[] { "DepartmentID" }, "IX_EmployeeDepartmentHistory_DepartmentID");

                    b.HasIndex(new[] { "ShiftID" }, "IX_EmployeeDepartmentHistory_ShiftID");

                    b.ToTable("EmployeeDepartmentHistory", "HumanResources", t =>
                        {
                            t.HasComment("Employee department transfers.");
                        });
                });

            modelBuilder.Entity("Data.Models.EmployeePayHistory", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number. Foreign key to Employee.BusinessEntityID.");

                    b.Property<DateTime>("RateChangeDate")
                        .HasColumnType("datetime")
                        .HasComment("Date the change in pay is effective");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<byte>("PayFrequency")
                        .HasColumnType("tinyint")
                        .HasComment("1 = Salary received monthly, 2 = Salary received biweekly");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money")
                        .HasComment("Salary hourly rate.");

                    b.HasKey("BusinessEntityID", "RateChangeDate")
                        .HasName("PK_EmployeePayHistory_BusinessEntityID_RateChangeDate");

                    b.ToTable("EmployeePayHistory", "HumanResources", t =>
                        {
                            t.HasComment("Employee pay history.");
                        });
                });

            modelBuilder.Entity("Data.Models.JobCandidate", b =>
                {
                    b.Property<int>("JobCandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for JobCandidate records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCandidateID"));

                    b.Property<int?>("BusinessEntityID")
                        .HasColumnType("int")
                        .HasComment("Employee identification number if applicant was hired. Foreign key to Employee.BusinessEntityID.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Resume")
                        .HasColumnType("xml")
                        .HasComment("Résumé in XML format.");

                    b.HasKey("JobCandidateID")
                        .HasName("PK_JobCandidate_JobCandidateID");

                    b.HasIndex(new[] { "BusinessEntityID" }, "IX_JobCandidate_BusinessEntityID");

                    b.ToTable("JobCandidate", "HumanResources", t =>
                        {
                            t.HasComment("Résumés submitted to Human Resources by job applicants.");
                        });
                });

            modelBuilder.Entity("Data.Models.Shift", b =>
                {
                    b.Property<byte>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasComment("Primary key for Shift records.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ShiftID"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasComment("Shift end time.");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasComment("Date and time the record was last updated.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Shift description.");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasComment("Shift start time.");

                    b.HasKey("ShiftID")
                        .HasName("PK_Shift_ShiftID");

                    b.HasIndex(new[] { "Name" }, "AK_Shift_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "StartTime", "EndTime" }, "AK_Shift_StartTime_EndTime")
                        .IsUnique();

                    b.ToTable("Shift", "HumanResources", t =>
                        {
                            t.HasComment("Work shift lookup table.");
                        });
                });

            modelBuilder.Entity("Data.Models.vAdditionalContactInfo", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMailAddress")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EMailSpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailTelephoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddressSpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelephoneSpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vAdditionalContactInfo", "Person");
                });

            modelBuilder.Entity("Data.Models.vStateProvinceCountryRegion", b =>
                {
                    b.Property<string>("CountryRegionCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CountryRegionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsOnlyStateProvinceFlag")
                        .HasColumnType("bit");

                    b.Property<string>("StateProvinceCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<int>("StateProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("StateProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TerritoryID")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vStateProvinceCountryRegion", "Person");
                });

            modelBuilder.Entity("Data.Models.EmployeeDepartmentHistory", b =>
                {
                    b.HasOne("Data.Models.Employee", "BusinessEntity")
                        .WithMany("EmployeeDepartmentHistories")
                        .HasForeignKey("BusinessEntityID")
                        .IsRequired();

                    b.HasOne("Data.Models.Department", "Department")
                        .WithMany("EmployeeDepartmentHistories")
                        .HasForeignKey("DepartmentID")
                        .IsRequired();

                    b.HasOne("Data.Models.Shift", "Shift")
                        .WithMany("EmployeeDepartmentHistories")
                        .HasForeignKey("ShiftID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");

                    b.Navigation("Department");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Data.Models.EmployeePayHistory", b =>
                {
                    b.HasOne("Data.Models.Employee", "BusinessEntity")
                        .WithMany("EmployeePayHistories")
                        .HasForeignKey("BusinessEntityID")
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("Data.Models.JobCandidate", b =>
                {
                    b.HasOne("Data.Models.Employee", "BusinessEntity")
                        .WithMany("JobCandidates")
                        .HasForeignKey("BusinessEntityID");

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("Data.Models.Department", b =>
                {
                    b.Navigation("EmployeeDepartmentHistories");
                });

            modelBuilder.Entity("Data.Models.Employee", b =>
                {
                    b.Navigation("EmployeeDepartmentHistories");

                    b.Navigation("EmployeePayHistories");

                    b.Navigation("JobCandidates");
                });

            modelBuilder.Entity("Data.Models.Shift", b =>
                {
                    b.Navigation("EmployeeDepartmentHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
